language: php
php:
    - 7.0
    - 7.1

script:
    - vendor/bin/phpstan analyse -l 5 -c phpstan.neon src

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
